### ISSUE TITLE
[bug] www.gorillatoolkit.org/pkg/* are down

### ISSUE THREAD

**Issue by moveonup** [gorilla/mux#594]
www.gorillatoolkit.org/pkg/* are down since weeks and shows an "Internal Error" error

**Comment by elithrar** [comment]
These have been fixed and now all redirect to GitHub.

**Comment by moveonup** [comment]
It does not really fix it. Why are these very useful pages now only available on archive.org?

**Comment by elithrar** [comment]
Because the package parsing code is broken, and I unfortunately do not have the time to fix it.

If you want to fix it directly, please submit a PR to `gorilla/site`.
